package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Guests implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "How many guests")
   private int min_number;

   @org.kie.api.definition.type.Label(value = "How many max number of guests?")
   private int max_num;

   public Guests()
   {
   }

   public int getMin_number()
   {
      return this.min_number;
   }

   public void setMin_number(int min_number)
   {
      this.min_number = min_number;
   }

   public int getMax_num()
   {
      return this.max_num;
   }

   public void setMax_num(int max_num)
   {
      this.max_num = max_num;
   }

   public Guests(int min_number, int max_num)
   {
      this.min_number = min_number;
      this.max_num = max_num;
   }

}