package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Guests implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Guests() {
    }

}