package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Season implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Season")
   private Season name;

   public Season()
   {
   }

   public org.kie.example.project1.Season getName()
   {
      return this.name;
   }

   public void setName(org.kie.example.project1.Season name)
   {
      this.name = name;
   }

   public Season(org.kie.example.project1.Season name)
   {
      this.name = name;
   }

}